Remove prime ng
astrutz/amazing-frontend pull request #32
Opened 2024-04-10 16:58 UTC by MUppenkamp

![image](https://github.com/astrutz/amazing-frontend/assets/35469083/7b068a20-5369-4ed0-b66a-cfe0bb23cca6)

2024-04-10 17:03 UTC, astrutz requested changes

2024-04-10 17:03 UTC, astrutz commented on src/app/components/create/create.component.html
> +        <label for="description">Beschreibung (ptional)</label>
Typo

2024-04-10 17:03 UTC, astrutz commented on src/app/components/create/create.component.html
> +              [max]="180"
Unbedingt bitte Digits reinnehmen wieder

2024-04-10 17:03 UTC, astrutz commented on src/app/components/create/create.component.ts
> +        // TODO Show error message
Wann todo?

2024-04-11 07:12 UTC, MUppenkamp commented on src/app/components/create/create.component.html
> +              [max]="180"
Was meinst du? meinst minFractionDigits und maxFractionDigits? Das kam ja von primeNG.

2024-04-11 07:13 UTC, MUppenkamp commented on src/app/components/create/create.component.ts
> +        // TODO Show error message
Im anderen Issue https://github.com/astrutz/amazing-frontend/issues/13

2024-04-11 11:34 UTC, astrutz commented on src/app/components/create/create.component.html
> +              [max]="180"
Ja, aber das müssen wir irgendwie nachbilden hier. Vielleicht mit [Step](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input/number#step)

2024-05-06 13:04 UTC, astrutz commented
We also need a uploader field in `/create`

2024-06-13 13:33 UTC, MUppenkamp commented on src/app/components/create/create.component.html
> +        <label for="description">Beschreibung (ptional)</label>
Ist eh nicht optional, nehme ich raus

2024-06-13 14:21 UTC, astrutz approved these changes

2024-06-13 14:22 UTC, merged

2024-06-26 12:51 UTC, astrutz commented
Closes #13